# ===================================
#  Relation Behavior Config
# ===================================

event:
    label: Event
    list: ~/plugins/beysong/events/models/event/columns.yaml
    form: ~/plugins/beysong/events/models/event/fields.yaml
