# ===================================
#  Relation Behavior Config
# ===================================

phone:
    label: Event
    form: ~/plugins/beysong/events/models/event/fields.yaml
    list: ~/plugins/beysong/events/models/event/columns.yaml
