# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Person

# Model Form Field configuration
form: ~/plugins/beysong/events/models/event/fields.yaml

# Model Class name
modelClass: Beysong\Events\Models\Event

# Default redirect location
defaultRedirect: beysong/events/events

# Create page
create:
    title: Create Event
    redirect: beysong/events/events/update/:id
    redirectClose: beysong/events/events

# Update page
update:
    title: Edit Event
    redirect: beysong/events/events
    redirectClose: beysong/events/events

# Preview page
preview:
    title: Preview Event