# ===================================
#  Relation Behavior Config
# ===================================

order_details:
    label: OrderDetail
    list: ~/plugins/beysong/events/models/orderdetail/columns.yaml
    form: ~/plugins/beysong/events/models/orderdetail/fields.yaml
    manage:
        context: relation

