# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: OrderDetail

# Model Form Field configuration
form: $/beysong/events/models/orderdetail/fields.yaml

# Model Class name
modelClass: Beysong\Events\Models\OrderDetail

# Default redirect location
defaultRedirect: beysong/events/orderdetails

# Create page
create:
    title: Create Order Detail
    redirect: beysong/events/orderdetails/update/:id
    redirectClose: beysong/events/orderdetails

# Update page
update:
    title: Edit Order Detail
    redirect: beysong/events/orderdetails
    redirectClose: beysong/events/orderdetails

# Preview page
preview:
    title: Preview Order Detail