# ===================================
#  Relation Behavior Config
# ===================================

orders:
    label: Order
    list: ~/plugins/beysong/events/models/order/columns.yaml
    form: ~/plugins/beysong/events/models/order/fields.yaml
